/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/[...path]/': RouteRecordInfo<'/[...path]/', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/logout/': RouteRecordInfo<'/auth/logout/', '/auth/logout', Record<never, never>, Record<never, never>>,
    '/media/collection/[...mediaPath]': RouteRecordInfo<'/media/collection/[...mediaPath]', '/media/collection/:mediaPath(.*)', { mediaPath: ParamValue<true> }, { mediaPath: ParamValue<false> }>,
    '/media/collections/': RouteRecordInfo<'/media/collections/', '/media/collections', Record<never, never>, Record<never, never>>,
    '/media/consume/manga/[...mediaPath]': RouteRecordInfo<'/media/consume/manga/[...mediaPath]', '/media/consume/manga/:mediaPath(.*)', { mediaPath: ParamValue<true> }, { mediaPath: ParamValue<false> }>,
    '/media/consume/watch/[...mediaPath]': RouteRecordInfo<'/media/consume/watch/[...mediaPath]', '/media/consume/watch/:mediaPath(.*)', { mediaPath: ParamValue<true> }, { mediaPath: ParamValue<false> }>,
    '/media/details/[...mediaPath]': RouteRecordInfo<'/media/details/[...mediaPath]', '/media/details/:mediaPath(.*)', { mediaPath: ParamValue<true> }, { mediaPath: ParamValue<false> }>,
    '/media/explorer/[[mediaPath]]*': RouteRecordInfo<'/media/explorer/[[mediaPath]]*', '/media/explorer/:mediaPath?*', { mediaPath?: ParamValueZeroOrOne<true> }, { mediaPath?: ParamValueZeroOrOne<false> }>,
    '/media/list/': RouteRecordInfo<'/media/list/', '/media/list', Record<never, never>, Record<never, never>>,
    '/media/search/': RouteRecordInfo<'/media/search/', '/media/search', Record<never, never>, Record<never, never>>,
    '/panel': RouteRecordInfo<'/panel', '/panel', Record<never, never>, Record<never, never>>,
    '/panel/': RouteRecordInfo<'/panel/', '/panel', Record<never, never>, Record<never, never>>,
    '/panel/problems/': RouteRecordInfo<'/panel/problems/', '/panel/problems', Record<never, never>, Record<never, never>>,
    '/panel/settings/': RouteRecordInfo<'/panel/settings/', '/panel/settings', Record<never, never>, Record<never, never>>,
    '/panel/statistics/': RouteRecordInfo<'/panel/statistics/', '/panel/statistics', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
