name: Build and Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # manual trigger

jobs:
  build:
    permissions:
      contents: write  # allow to create a release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: src/web-ui/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: src/web-ui/
      - name: Build
        run: npm run build
        working-directory: src/web-ui/
      - name: Make Archive
        run: tar -cvz -C src/web-ui/dist/ -f "web-ui.tgz" .
      - name: Set now env
        run: echo "NOW=$(date --utc --iso-8601=seconds)" >> $GITHUB_OUTPUT
        id: date
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: false
          prerelease: false
          title: "Jarklin-Web Build (${{ steps.date.outputs.NOW }})"
          files: |
            web-ui.tgz
